//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2026 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 23/08/2026 12:48:45
//
//===========================================================================================
//
#pragma once

#ifndef AUTOMATICVERSIONHEADER_H
#define AUTOMATICVERSIONHEADER_H    1

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"SmartInfo"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"SmartInfo (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"SmartInfo (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"SmartInfo"
#define PROGRAM_REGKEY  L"Macallan\\SmartInfo"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\SmartInfo"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "SmartInfo"
#ifdef _WIN64
#define PROGRAM_NAME_P  "SmartInfo (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "SmartInfo (x86 MBCS)"
#endif
#define PROGRAM_SECT    "SmartInfo"
#define PROGRAM_REGKEY  "Macallan\\SmartInfo"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\SmartInfo"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Sun Aug 23 12:48"
#define PROGRAM_DATE_F  L"Sun Aug 23 12:48 2026"
#define PROGRAM_YEAR    L"2026"
#define PROGRAM_TIME    L"2026/08/23 12:48:45"
#else
#define PROGRAM_DATE    "Sun Aug 23 12:48"
#define PROGRAM_DATE_F  "Sun Aug 23 12:48 2026"
#define PROGRAM_YEAR    "2026"
#define PROGRAM_TIME    "2026/08/23 12:48:45"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"1.0.05.006"
#define PROGRAM_INSTALL L"1.0.05006"
#define PROGRAM_VER_NUM 10005006
#define PROGRAM_BUILD   L"78"
#define PROGRAM_TITLE   L"Smart Info"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"Smart Info (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"Smart Info (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "1.0.05.006"
#define PROGRAM_INSTALL "1.0.05006"
#define PROGRAM_VER_NUM 10005006
#define PROGRAM_BUILD   "78"
#define PROGRAM_TITLE   "Smart Info"
#ifdef _WIN64
#define PROGRAM_TITLE_P "Smart Info (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "Smart Info (x86 MBCS)"
#endif
#endif

#endif

